// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"database/sql"
)

type UserDetail struct {
	ID           int32          `json:"id"`
	Email        string         `json:"email"`
	UserPassword sql.NullString `json:"user_password"`
	Created      sql.NullTime   `json:"created"`
	Updated      sql.NullTime   `json:"updated"`
	Deleted      sql.NullTime   `json:"deleted"`
}
