// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"context"
)

type Querier interface {
	QueryAddUser(ctx context.Context, arg QueryAddUserParams) error
	QueryCheckUserByEmail(ctx context.Context, email string) (UserDetail, error)
	QueryGetAlluser(ctx context.Context) ([]UserDetail, error)
	QueryGetUserById(ctx context.Context, id int32) (UserDetail, error)
}

var _ Querier = (*Queries)(nil)
